GET http://localhost:4000/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTY2NDY1MDc4OSwiZXhwIjoxNjY0NjUwODQ5fQ.bsfp5wgtrzY7TqEbpInyXDuWq0Y4UEVzJHqydFqdh2g

###

POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "username": "admin"
}

###

POST http://localhost:4000/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJqaW0iLCJpYXQiOjE2NjE3MDQyOTgsImV4cCI6MTY2MTcwNzg5OH0.4MzSAlYjh7hqkPorbYuh1BjjcA_U0w4Uc741jvGLc2E"
}

###

DELETE http://localhost:4000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTY2NDY0OTYxMCwiZXhwIjoxNjY0NjQ5NjcwfQ.kI3chs2OP3yPZvhiavheyBFkdd7Hf6w93VOhsU5nsZI

###
GET http://localhost:4000/galleries
